### PR TITLE
fix #51135 make CFS quota period configurable

### PR DESCRIPTION
**Pull request by BenPope**
adds a cli flag and config option to kubelet to be able to set cpu.cfs_period and defaults to 100ms as before

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Looks reasonable to me. Have you got a ref for the image you created? 

Should we set up some automation for builds for this fork? If we can build the hyperkube binary in a container in a way compatible with quay that would make it easy to create new images

**Comment by BenPope** [comment]
Whats a ref? This: http://quay.io/ben_pope/hyperkube-amd64:v1.9.3-cfs-quota-period ?

I looked at setting up quay for building, but wasn't sure I wanted to give it access to my (Pushers) private repos, and doing it via a manual github webhook wasn't working.  You can point quay.io to a Dockerfile, but I don't know how you tell it which command to run before building it.

**Comment by JoelSpeed** [comment]
Yeah that's close enough thanks, I was looking for the bit I need to do a `docker pull <image_ref>`

Quay already has access to pusher repos for some stuff anyway. I don't think you can do complex builds like that, we may have to make our own Dockerfile if we want to do an auto build, or using wercker or something else with more powers

**Comment by wonderhoss** [comment]
I would also not be opposed to making this repo public.
@BenPope how hard would it be to run the standard tests in CI?

**Comment by JoelSpeed** [comment]
@BenPope We can close this now right?

**Comment by BenPope** [comment]
Merged upstream

**Pull request closed without merging**
